### ISSUE TITLE
询问代码开源时间

### ISSUE THREAD

**Issue by TaylorRex** [XuzheZ/MAPSeg#1]
感谢您杰出的贡献，我对您的研究很有兴趣，不知道您的代码将何时开源？
祝好！

**Comment by XuzheZ** [comment]
您好，感谢您对我们工作的关注！我们计划于四月底前上传全部代码，详细原因请参照更新后的readme

Stay tuned!

**Comment by XuzheZ** [comment]
Hi very much appreciate your patience! The codes are now released! We are still working on integrating FL into this codespace and hope to share more useful suggestions for training.
