### ISSUE TITLE
Release of code

### ISSUE THREAD

**Issue by niusj03** [XuzheZ/MAPSeg#2]
Hi awesome work! Just kind ask when can release all code to facilitate reproduction?

**Comment by XuzheZ** [comment]
Sorry, I got stuck by some conference, and the code is not clean enough... We will definitely upload it before the CVPR conference!

**Comment by XuzheZ** [comment]
Hi very much appreciate your patience! The codes are now released! We are still working on integrating FL into this codespace and hope to share more useful suggestions for training.

**Comment by niusj03** [comment]
Many thanks for your hard-working contributions. That means everything to us!

Best wishes


From: Xuzhe Johnny Zhang ***@***.***>
Date: Wednesday, 19 June 2024 at 23:35
To: XuzheZ/MAPSeg ***@***.***>
Cc: Shengjie Niu ***@***.***>, Author ***@***.***>
Subject: Re: [XuzheZ/MAPSeg] Release of code (Issue #2)

Hi very much appreciate your patience! The codes are now released! We are still working on integrating FL into this codespace and hope to share more useful suggestions for training.

**Comment by XuzheZ** [comment]
No problem! Sorry for the wait - there are too many things going on, and I was significantly delayed in cleaning up the code. Please ensure that you go through the README and all comments in the code, and if you have other questions, please feel free to open an issue. 

Best,
Xuzhe
