### ISSUE TITLE
Validation error when depth (z-axis) smaller than patch size 96

### ISSUE THREAD

**Issue by kmin940** [XuzheZ/MAPSeg#4]
Dear authors, 

Thank you for your prompt reply on resolving the training error on the custom dataset! However, I encountered another error while I am running on the custom dataset. May I also ask how to resolve this? I have disabled the validation, but I would very like to run the inference after the training is done! Thank you in advance.

```(epoch: 1, iters: 0, time: 0.329) src_seg_loss: 2.628 src_seg_loss_masked: 2.623 src_seg_loss_aux: 2.582 src_seg_loss_aux_masked: 2.535 src_cos_reg: 0.882 src_cos_reg_masked: 0.878 
Traceback (most recent call last):
  File "/home/sumin2/Documents/MAPSeg/train.py", line 127, in <module>
    save_best = train_solver.validation(epoch)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sumin2/Documents/MAPSeg/model/solver.py", line 493, in validation
    tmp_pred = self.infer_single_scan(tmp_scans)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sumin2/miniconda3/envs/mapseg/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sumin2/Documents/MAPSeg/model/solver.py", line 405, in infer_single_scan
    scan_patches, _, tmp_idx = util.patch_slicer(tmp_scans, tmp_scans, self.cfg.data.patch_size,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sumin2/Documents/MAPSeg/model/utils/util.py", line 242, in patch_slicer
    for z_idx in z_steps:
  File "/home/sumin2/Documents/MAPSeg/model/utils/util.py", line 180, in _gen_indices
    assert i2 >= k, 'sample size has to be bigger than the patch size'
           ^^^^^^^
AssertionError: sample size has to be bigger than the patch size
```

**Comment by XuzheZ** [comment]
Hello!

Sorry for the late reply. I've pushed a commit to 
1. address this error that the validation and inference code won't support the scan with dimension(s) smaller than the patch size. 
2. Incorrect padding for data loader in my previous commit will lead to a mismatch in location in the local patch and global scan. 
So please try to pull the latest code and rerun the MPL training (as the previous padding was wrong). And the validation (and test/inference) should work for data with dimension(s) smaller than patch size now.

If your data has dimension(s) that is generally smaller than the patch size, you may consider changing the patch size. For instance, if your data is mostly like (200,200,70), you can try patch size at (96,96,48). But this will require retraining from scratch (from MAE pretraining).

Thank you and please let me know if you encounter other questions!

Happy training,
Xuzhe
